ERROR - 2022-12-27 08:15:20 --> mysqli_sql_exception: Duplicate entry 'muh93@gmail.com' for key 'email' in C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `users` ...', 0)
#1 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\xampp\htdocs\restfulapi\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\xampp\htdocs\restfulapi\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\restfulapi\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\restfulapi\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\restfulapi\app\Controllers\User.php(131): CodeIgniter\Model->update('4', Array)
#8 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(907): App\Controllers\User->update('4')
#9 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\restfulapi\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-12-27 08:16:24 --> mysqli_sql_exception: Duplicate entry 'muh93@gmail.com' for key 'email' in C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `users` ...', 0)
#1 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\xampp\htdocs\restfulapi\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\xampp\htdocs\restfulapi\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\restfulapi\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\restfulapi\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\restfulapi\app\Controllers\User.php(131): CodeIgniter\Model->update('4', Array)
#8 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(907): App\Controllers\User->update('4')
#9 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\restfulapi\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-27 19:42:29 --> callback_check_user_email is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 323.
 1 SYSTEMPATH\Validation\Validation.php(323): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('callback_check_user_email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'muh@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\User.php(113): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\User->update('4')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-27 19:42:57 --> callback_check_user_email is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 323.
 1 SYSTEMPATH\Validation\Validation.php(323): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('callback_check_user_email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'muh@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\User.php(113): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\User->update('4')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-27 19:43:05 --> callback_check_user_email is not a valid rule.
in SYSTEMPATH\Validation\Validation.php on line 323.
 1 SYSTEMPATH\Validation\Validation.php(323): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('callback_check_user_email')
 2 SYSTEMPATH\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'muh1@gmail.com', [...], [...])
 3 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 4 APPPATH\Controllers\User.php(113): CodeIgniter\Controller->validate([...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\User->update('4')
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-27 20:09:38 --> mysqli_sql_exception: Duplicate entry 'muhpp@gmail.com' for key 'email' in C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `users` ...', 0)
#1 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\xampp\htdocs\restfulapi\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\xampp\htdocs\restfulapi\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\restfulapi\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\restfulapi\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\restfulapi\app\Controllers\User.php(133): CodeIgniter\Model->update('1', Array)
#8 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(907): App\Controllers\User->update('1')
#9 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\restfulapi\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-12-27 20:36:01 --> mysqli_sql_exception: Duplicate entry 'muh@gmail.com' for key 'email' in C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `users` ...', 0)
#1 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `users` ...')
#2 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `users` ...')
#3 C:\xampp\htdocs\restfulapi\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `users` ...', Array, false)
#4 C:\xampp\htdocs\restfulapi\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\restfulapi\system\BaseModel.php(865): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\restfulapi\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\restfulapi\app\Controllers\User.php(130): CodeIgniter\Model->update('4', Array)
#8 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(907): App\Controllers\User->update('4')
#9 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#10 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\restfulapi\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-12-27 21:40:36 --> mysqli_sql_exception: Unknown column '$id' in 'where clause' in C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\restfulapi\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\restfulapi\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\restfulapi\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('muh93@gmail.com', 'email ', Array, NULL)
#6 C:\xampp\htdocs\restfulapi\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'muh93@gmail.com', Array, Array)
#7 C:\xampp\htdocs\restfulapi\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\restfulapi\app\Controllers\User.php(140): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(907): App\Controllers\User->update('4')
#10 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\restfulapi\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-12-27 21:40:55 --> mysqli_sql_exception: Unknown column '$id' in 'where clause' in C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\restfulapi\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\restfulapi\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\restfulapi\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('muh00@gmail.com', 'email ', Array, NULL)
#6 C:\xampp\htdocs\restfulapi\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'muh00@gmail.com', Array, Array)
#7 C:\xampp\htdocs\restfulapi\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\restfulapi\app\Controllers\User.php(140): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(907): App\Controllers\User->update('4')
#10 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\restfulapi\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2022-12-27 21:53:52 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':4:
 LIMIT 1' at line 4 in C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\restfulapi\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT 1\nFROM `...', 0)
#1 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\restfulapi\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\restfulapi\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\restfulapi\system\Validation\Rules.php(142): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\restfulapi\system\Validation\Validation.php(315): CodeIgniter\Validation\Rules->is_unique('muh00@gmail.com', 'email', Array, NULL)
#6 C:\xampp\htdocs\restfulapi\system\Validation\Validation.php(175): CodeIgniter\Validation\Validation->processRules('email', 'email', 'muh00@gmail.com', Array, Array)
#7 C:\xampp\htdocs\restfulapi\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\restfulapi\app\Controllers\User.php(140): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(907): App\Controllers\User->update('4')
#10 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#11 C:\xampp\htdocs\restfulapi\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\restfulapi\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
